jobs:
- job: CreateEC2
  displayName: Create AWS Infrastructure
  pool:
    name: 'New agent'   # Replace with your self-hosted agent pool name
    
  variables:
  - group: New variable group 08-Sep

  steps:
  - script: |
    python -m venv venv
    source venv/bin/activate

    pip install --upgrade pip
    pip install ansible boto3 botocore amazon.aws

    ansible-galaxy collection install amazon.aws

    # Export AWS credentials from pipeline variables
    export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
    export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
    export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)

    # Run teardown playbook
    ansible-playbook teardown.yml

  displayName: Destroy AWS Infrastructure
